### ISSUE TITLE
Question regarding CulebraTester2 UI beta availability

### ISSUE THREAD

**Issue by 46cv8** [dtmilano/CulebraTester2-public#7]
I apologize as this is not an issue so much as a question.

At the bottom of the readme you show a video of what looks like a fantastic viewer too that would work with your software stack.
https://www.youtube.com/watch?v=prE0aKoMLfc

I had been trying to automate an app with Appium but the rapid updates meant that I wasn't able to view the structure using uiautomatorviewer, or click on buttons due to the continuous stream of "Accessibility Events". 

https://stackoverflow.com/questions/70670116/android-get-current-ui-layout-without-uiautomator

I have managed to get down your tools and can successfully dump the structure and I am hoping to move over from uiautomatorviewer and Appium to using your tool-sets. I haven't attempted to actually perform any automation tasks with https://github.com/dtmilano/CulebraTester2-client just yet but will do shortly.

I am curious though where the CulebraTester2 UI beta can be downloaded from (if it is available). It's a little difficult for me to find the correspond buttons for the app I'm working on. So having a UI like this is pretty much essential. If you have any details about it's availability I would very much appreciate hearing from you.

**Comment by dtmilano** [comment]
@46cv8 `culebra` can still generate python code that's compatible with **CulebraTester2-public** if you choose the right option.
This is a working example: https://stackoverflow.com/questions/72352682/adb-force-real-touch/72370929#72370929

The main difference between the new tool (the one from the video) is that it can also generate other languages (Kotlin, Java, javascript/typescript, etc.) and it's web-based instead of Tkinter (which is kind of ugly).

If you have more questions or encounter some problem with `culebra` don't hesitate to open an issue here or ask at [StackOverflow](https://stackoverflow.com/questions/tagged/androidviewclient).
