### ISSUE TITLE
How to get the code generator

### ISSUE THREAD

**Issue by AnunayaThakureb** [dtmilano/CulebraTester2-public#9]
When I start the server and go to the local host 

![image](https://user-images.githubusercontent.com/105661388/170430598-5e0f3874-4db0-45cf-8bde-1f05cc5a03f8.png)

when go to help it says 

![image](https://user-images.githubusercontent.com/105661388/170430937-1b1bff34-af11-4d04-b740-0481142106f7.png)

How to get the code generator?

**Comment by anunay1** [comment]
@dtmilano Can you please help?

**Comment by szymondziedziel** [comment]
I remember that I had the same problem someday.

When I hit `http://localhost:9987` I get same thing as you on the first screen
When I hit `http://localhost:9987/help` I get same thing as you shown on the second screen

When I hit `http://localhost:9987/v2/uiDevice/dumpWindowHierarchy?format=xml` I get dumped hierarchy in `xml`. I remember that I had problem with missing `v2` in URL
When I hit `http://localhost:9987/v2/uiDevice/screenshot` I get screenshot from device

Be aware that I have different port than you

**Comment by anunay1** [comment]
Thanks @szymondziedziel for the response, but what I am looking for is how to get this window:
![image](https://user-images.githubusercontent.com/7989610/170579393-3f1dfe1d-b721-4445-a674-4f7a58ed5648.png)

**Comment by dtmilano** [comment]
@anunay1 the screenshot is from a discontinued product and it's no longer available.
There will be a replacement in the future and a preview is in this [video](https://www.youtube.com/watch?feature=player_embedded&v=prE0aKoMLfc)

**Comment by AnunayaThakureb** [comment]
Thanks @dtmilano for the response. Any plans when can we have the future replacement.

**Comment by dtmilano** [comment]
@AnunayaThakureb `culebra` can still generate python code that's compatible with **CulebraTester2-public** if you choose the right option. 
This is a working example: https://stackoverflow.com/questions/72352682/adb-force-real-touch/72370929#72370929

The main difference of the new tool (the one from the video) is that it can also generate other languages (Kotlin, Java, javascript/typescript, etc.) and it's web-based instead of *Tkinter*.

If you have more questions or encounter some problem with `culebra` don't hesitate to open an issue here or ask at [StackOverflow](https://stackoverflow.com/questions/tagged/androidviewclient).

**Comment by anunay1** [comment]
Thanks @dtmilano  for the response and excellent support. Any plans by when you can provide the web based interface, I am support to test it.
